-- E TO E schema for Supabase (PostgreSQL). Ported from the live SQL Server database MoiSei.
-- Table and column names are unchanged so the API queries only need dialect changes.

create sequence if not exists users_serial_number_seq;

create table users (
    id              integer generated by default as identity primary key,
    husband_name    text        not null,
    wife_name       text,
    husband_job     text,
    phone_number    varchar(30) not null,
    family_deity    text,
    email           text,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    is_active       boolean     not null default true,
    password_hash   text,
    search_alias    text,
    native_place    text,
    current_place   text,
    wife_job        text,
    others          text,
    initial         text,
    notes           text,
    serial_number   integer     default nextval('users_serial_number_seq'),
    is_thaimama     boolean     not null default false,
    constraint uq_users_phone_number unique (phone_number)
);
create index ix_users_husband_name on users (husband_name);

create table event (
    event_id        integer generated by default as identity primary key,
    event_name      text        not null,
    event_date      date        not null,
    event_place     text,
    event_location  text,
    -- The single receiving family; locked in by the first contribution when left NULL.
    host_user_id    integer references users (id),
    is_active       boolean     not null default true,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create table transactions (
    transaction_id   integer generated by default as identity primary key,
    description      text,
    created_at       timestamptz not null default now(),
    transaction_date date        not null default ((now() at time zone 'Asia/Kolkata')::date)
);

create table journal_entries (
    journal_entry_id integer generated by default as identity primary key,
    transaction_id   integer       not null references transactions (transaction_id) on delete cascade,
    user_id          integer       not null references users (id),
    event_id         integer       not null references event (event_id),
    entry_type       varchar(12)   not null,
    amount           numeric(12,2) not null,
    constraint ck_journal_entries_entry_type check (entry_type in ('CONTRIBUTED', 'RECEIVED')),
    constraint ck_journal_entries_amount check (amount > 0)
);
create index ix_journal_entries_transaction on journal_entries (transaction_id);
create index ix_journal_entries_user on journal_entries (user_id);
create index ix_journal_entries_event on journal_entries (event_id, entry_type);

create table staff_accounts (
    staff_id     integer generated by default as identity primary key,
    display_name text        not null,
    pin_hash     text        not null,
    role         text        not null default 'counter',
    is_active    boolean     not null default true,
    created_at   timestamptz not null default now(),
    constraint ck_staff_accounts_role check (role in ('admin', 'counter'))
);

create table transaction_denominations (
    transaction_id integer not null references transactions (transaction_id) on delete cascade,
    denomination   integer not null,
    note_count     integer not null check (note_count > 0),
    primary key (transaction_id, denomination)
);

create table transaction_collectors (
    transaction_id integer primary key references transactions (transaction_id) on delete cascade,
    staff_id       integer     not null references staff_accounts (staff_id),
    collected_at   timestamptz not null default now()
);
create index ix_transaction_collectors_staff on transaction_collectors (staff_id);

-- Records one contribution atomically (a function body is a single transaction) and returns its transaction_id.
create or replace function process_contribution(
    p_contributor_id integer,
    p_receiver_id    integer,
    p_event_id       integer,
    p_amount         numeric
) returns integer
language plpgsql
as $$
declare
    v_host_user_id integer;
    v_event_date   date;
    v_today        date := (now() at time zone 'Asia/Kolkata')::date;
    v_tx_id        integer;
begin
    if p_contributor_id = p_receiver_id then
        raise exception 'Contributor and Receiver cannot be the same user.';
    end if;
    if p_amount <= 0 then
        raise exception 'Contribution amount must be greater than zero.';
    end if;
    if not exists (select 1 from users where id = p_contributor_id and is_active) then
        raise exception 'Contributor User ID does not exist.';
    end if;
    if not exists (select 1 from users where id = p_receiver_id and is_active) then
        raise exception 'Receiver User ID does not exist.';
    end if;

    -- Row lock so two counters cannot lock in different hosts for the same event at once.
    select host_user_id, event_date into v_host_user_id, v_event_date
    from event where event_id = p_event_id and is_active
    for update;
    if not found then
        raise exception 'Event ID does not exist or is inactive.';
    end if;

    if v_today < v_event_date then
        raise exception 'Contribution date cannot be before the event date.';
    end if;
    if v_host_user_id is not null and v_host_user_id <> p_receiver_id then
        raise exception 'This event already has a different receiver (host) assigned.';
    end if;

    if v_host_user_id is null then
        update event set host_user_id = p_receiver_id, updated_at = now() where event_id = p_event_id;
    end if;

    insert into transactions (description)
    values ('Contribution from User ' || p_contributor_id || ' to User ' || p_receiver_id)
    returning transaction_id into v_tx_id;

    insert into journal_entries (transaction_id, user_id, event_id, entry_type, amount)
    values (v_tx_id, p_contributor_id, p_event_id, 'CONTRIBUTED', p_amount),
           (v_tx_id, p_receiver_id,    p_event_id, 'RECEIVED',    p_amount);

    return v_tx_id;
end;
$$;

-- The API connects directly as the database owner, which bypasses RLS. Enabling RLS with no policies
-- blocks the public Supabase Data API (anon key), which would otherwise expose these tables.
alter table users                     enable row level security;
alter table event                     enable row level security;
alter table transactions              enable row level security;
alter table journal_entries           enable row level security;
alter table staff_accounts            enable row level security;
alter table transaction_denominations enable row level security;
alter table transaction_collectors    enable row level security;

revoke execute on function process_contribution(integer, integer, integer, numeric) from public, anon, authenticated;
