-- JSON snapshots remain text to match the API's serialized history response.
BEGIN;

CREATE TABLE IF NOT EXISTS public.user_change_history (
    history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES public.users(id),
    changed_by_staff_id integer NOT NULL REFERENCES public.staff_accounts(staff_id),
    changed_at timestamptz NOT NULL DEFAULT now(),
    before_json text NOT NULL,
    after_json text NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_user_change_history_changed_at
    ON public.user_change_history(changed_at DESC, history_id DESC);
CREATE INDEX IF NOT EXISTS ix_user_change_history_user_id
    ON public.user_change_history(user_id, changed_at DESC);

ALTER TABLE public.user_change_history ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.user_change_history FROM anon, authenticated;
COMMIT;
